apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helmchart.fullname" . }}
    chart: {{ include "helmchart.chart" . }}   
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "helmchart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ include "helmchart.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "helmchart.fullname" . }}-int
    chart: {{ include "helmchart.chart" . }}   
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ include "helmchart.fullname" . }}-int
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ include "helmchart.fullname" . }}-int