apiVersion: v1
kind: Service
metadata:  
  name: mediaencodingservice
  namespace: default  
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mediaencodingservice
  sessionAffinity: None
  type: ClusterIP

