image:
  registry:  sapphire.azurecr.io
  repository: sampleapi
  tag: "$(Build.BuildNumber)"
replicaCount: 2
resources:
  requests:
    memory: "200Mi"
    cpu: "25m"
  limits:
    memory: "500Mi"
    cpu: "50m"
ingressDomain: api-sapphire.dataservices-dev.doverfs.com
testDomain: sapphire-test.dataservices-dev.doverfs.com
gateway: sap-dev-gateway  
service:
  type: ClusterIP
  port: 9010
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  minReplicasInt: 2
  maxReplicasInt: 30
testgateway:
  enabled: false